packages:
  - "packages/*"
  - "examples/*"

packageExtensions:
  "@huggingface/transformers":
    dependencies:
      onnxruntime-common: 1.24.3

allowBuilds:
  "@google/genai": true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - '@mastra/core@1.41.0'
