// SPDX-License-Identifier: MIT
//
// Builds AGENTS.md — must state plainly what a coding agent CANNOT verify
// headlessly (LDT-21 requirement). An AGENTS.md implying headless
// verification is complete is worse than shipping none.

import type { ResolvedOptions } from "../options.js";

export function buildAgentsMd(opts: ResolvedOptions): string {
  const pipelineLine =
    opts.mode === "cascade"
      ? `${opts.stt} STT -> ${opts.reasoner} reasoner -> ${opts.tts} TTS (cascade)`
      : `${opts.realtime} realtime (speech-to-speech, no separate STT/TTS stages)`;

  return `# AGENTS.md

This project was generated by \`create-syrinx-agent\`.

Pipeline: ${pipelineLine}
Transport: ${opts.transport} · Runtime: ${opts.runtime}

## What a coding agent CAN verify here

- \`pnpm check:typecheck\` (\`tsc --noEmit\`) — the agent module and dev server compile.
- \`pnpm check:turn\` — runs \`syrinx turn --in test/fixtures/smoke.wav --agent ./src/agent.ts#createAgent --json\`.
  Given a fixture **with** a recorded expected transcript (a \`.json\` sidecar produced by the
  Studio's "Save as fixture"), this asserts the replayed transcript matches and **exits non-zero
  on drift** — a real regression check, not just a smoke test. The bundled \`test/fixtures/smoke.wav\`
  ships with no sidecar, so as generated this only proves the pipeline runs end-to-end and produces
  *some* transcript/reply/audio; record your own fixture with the Studio for an assertion that
  actually catches regressions.
- Exit codes and JSON output from \`syrinx turn\` / \`syrinx text\` — parseable, deterministic,
  scriptable.

Both checks need real provider credentials in \`.env\` (see \`.env.example\`) — without them
\`check:turn\` fails at the provider call, not at a code defect.

## What a coding agent CANNOT verify here

A coding agent can assert transcripts, exit codes, and latency numbers. It **cannot** judge:

- Whether barge-in feels natural (the timing a human perceives as responsive vs. jarring).
- Whether a pause reads as "thinking" or as a hang — same latency number, different human read.
- Whether a synthesized voice sounds warm, robotic, or off — TTS quality is a perceptual judgment.

Those need a human in the Syrinx Studio, listening. Do not treat a green \`check:turn\` as proof the
agent is pleasant to talk to — it only proves the transcript matched (or that the pipeline ran, for
the unsigned bundled fixture).

## \`tsx\` vs plain \`node\`

\`--agent\` pointed at a \`.ts\` module (as in the scripts above) needs \`tsx\` — Node's built-in type
stripping does not do TypeScript's \`.js\`-import-resolves-to-\`.ts\` remapping that this project's
imports rely on. Built JS (after a bundler step) runs fine under plain \`node\`. Every script this
generator wrote already invokes \`tsx\`; if you write your own, do the same for a \`.ts\` --agent target.

## Layout

- \`src/agent.ts\` — \`createAgent()\`, the \`--agent\` seam's factory export.
- \`scripts/dev-server.ts\` — local dev server (\`pnpm dev\`), wraps \`createAgent()\` in a
  ${opts.transport} transport host.
- \`test/fixtures/smoke.wav\` — bundled silence fixture for \`check:turn\`.
- \`.env.example\` — exactly the provider keys this combination needs.
`;
}
