// SPDX-License-Identifier: MIT
//
// Emits src/index.ts + wrangler.jsonc for --runtime cloudflare, mirroring
// examples/03-cf-agent-voice/src/index.ts and packages/cf-agents/README.md's
// `withVoice(Agent, { realtime | stt + tts, reasoner, transport })` peer-field shape. VAD/endpointing
// sidecars are not wired here yet (see the generator's report) — passing
// --vad/--endpointing with --runtime cloudflare is refused upstream.

import type { ResolvedOptions, Transport } from "../options.js";
import { STT_STAGE_PROVIDERS } from "../providers/stt.js";
import { TTS_STAGE_PROVIDERS } from "../providers/tts.js";
import { REASONER_PROVIDERS, SYSTEM_PROMPT_CONST } from "../providers/reasoner.js";
import { REALTIME_PROVIDERS } from "../providers/realtime.js";
import { CliError, EXIT_CODES } from "../exit-codes.js";
import type { EnvKeySpec, StageProvider } from "../providers/types.js";
import { collectEnvKeys } from "./env-example.js";

const SYSTEM_PROMPT = "You are a helpful voice assistant. Keep your replies short.";

function envRef(key: string): string {
  return `env.${key}`;
}

function importLine(className: string, from: string): string {
  return `import { ${className} } from "${from}";`;
}

function requireStage(provider: StageProvider | undefined, flag: string, value: string): StageProvider {
  if (provider === undefined) {
    throw new CliError(EXIT_CODES.USAGE, `--${flag} ${value} is not yet implemented by this generator`);
  }
  return provider;
}

/** `withVoice`'s documented `transport` option: "edge" | "twilio" | "telnyx" — no "smartpbx". */
function cfTransport(transport: Transport): "edge" | "twilio" | "telnyx" {
  if (transport === "browser") return "edge";
  if (transport === "twilio" || transport === "telnyx") return transport;
  throw new CliError(
    EXIT_CODES.USAGE,
    `--runtime cloudflare has no ${transport} transport binding in @kuralle-syrinx/cf-agents (only edge/twilio/telnyx) — use --transport browser, twilio, or telnyx`,
  );
}

function envInterface(keys: readonly EnvKeySpec[]): string {
  const lines = keys.map((k) => `  readonly ${k.key}: string;`);
  return `interface Env extends Record<string, unknown> {\n${lines.join("\n")}\n}`;
}

export function buildCloudflareWorkerSource(opts: ResolvedOptions): string {
  const transport = cfTransport(opts.transport);
  const envKeys = collectEnvKeys(opts);

  if (opts.mode === "cascade") {
    if (opts.vad !== undefined || opts.endpointing !== undefined) {
      throw new CliError(
        EXIT_CODES.USAGE,
        "--vad/--endpointing are not yet implemented for --runtime cloudflare by this generator",
      );
    }
    const stt = requireStage(STT_STAGE_PROVIDERS[opts.stt], "stt", opts.stt);
    const tts = requireStage(TTS_STAGE_PROVIDERS[opts.tts], "tts", opts.tts);
    const reasoner = REASONER_PROVIDERS[opts.reasoner];
    if (reasoner === undefined) {
      throw new CliError(EXIT_CODES.USAGE, `--reasoner ${opts.reasoner} is not yet implemented by this generator`);
    }

    const sttNew = stt.usesSocketFactory ? `new ${stt.className}(createWorkersSocket)` : `new ${stt.className}()`;
    const ttsNew = tts.usesSocketFactory ? `new ${tts.className}(createWorkersSocket)` : `new ${tts.className}()`;
    const needsWorkersSocket = stt.usesSocketFactory || tts.usesSocketFactory;

    const imports = [
      `import { Agent, routeAgentRequest } from "agents";`,
      `import { withVoice } from "@kuralle-syrinx/cf-agents";`,
      importLine(stt.className, stt.importFrom ?? stt.packageName),
      importLine(tts.className, tts.importFrom ?? tts.packageName),
      ...(needsWorkersSocket ? [`import { createWorkersSocket } from "@kuralle-syrinx/ws/workers";`] : []),
      ...reasoner.importLines(envRef),
    ];

    return `// SPDX-License-Identifier: MIT
//
// Cascade voice agent on Cloudflare Workers: ${opts.stt} STT -> ${opts.reasoner} reasoner -> ${opts.tts} TTS.
// Generated by create-syrinx-agent. Mirrors examples/03-cf-agent-voice and
// packages/cf-agents/README.md.

${imports.join("\n")}

${envInterface(envKeys)}

const ${SYSTEM_PROMPT_CONST} = ${JSON.stringify(SYSTEM_PROMPT)};

export class VoiceAgent extends withVoice<Env, typeof Agent<Env>>(Agent<Env>, {
  transport: "${transport}",
  stt: (env) => ({
    plugin: ${sttNew},
    config: {
${stt.configFields(envRef).map((f) => `      ${f},`).join("\n")}
    },
  }),
  tts: (env) => ({
    plugin: ${ttsNew},
    config: {
${tts.configFields(envRef).map((f) => `      ${f},`).join("\n")}
    },
  }),
  reasoner: (env) => {
${reasoner.preludeLines(envRef).map((l) => `    ${l}`).join("\n")}
    return ${reasoner.reasonerExpr};
  },
}) {}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    return (await routeAgentRequest(request, env)) ?? new Response("Not found", { status: 404 });
  },
};
`;
  }

  const realtime = REALTIME_PROVIDERS[opts.realtime];
  if (realtime === undefined) {
    throw new CliError(EXIT_CODES.USAGE, `--realtime ${opts.realtime} is not yet implemented by this generator`);
  }
  const imports = [
    `import { Agent, routeAgentRequest } from "agents";`,
    `import { withVoice } from "@kuralle-syrinx/cf-agents";`,
    `import { createWorkersSocket } from "@kuralle-syrinx/ws/workers";`,
    ...realtime.importLines,
  ];

  return `// SPDX-License-Identifier: MIT
//
// Speech-to-speech voice agent on Cloudflare Workers: ${opts.realtime} realtime.
// Generated by create-syrinx-agent. Mirrors examples/03-cf-agent-voice and
// packages/cf-agents/README.md.

${imports.join("\n")}

${envInterface(envKeys)}

export class VoiceAgent extends withVoice<Env, typeof Agent<Env>>(Agent<Env>, {
  transport: "${transport}",
  realtime: (env) => ${realtime.adapterExpr(envRef, "createWorkersSocket")},
}) {}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    return (await routeAgentRequest(request, env)) ?? new Response("Not found", { status: 404 });
  },
};
`;
}

export function buildWranglerJsonc(opts: ResolvedOptions): string {
  const wrangler = {
    $schema: "node_modules/wrangler/config-schema.json",
    name: opts.name,
    main: "src/index.ts",
    compatibility_date: "2026-06-01",
    compatibility_flags: ["nodejs_compat"],
    durable_objects: { bindings: [{ name: "VoiceAgent", class_name: "VoiceAgent" }] },
    migrations: [{ tag: "v1", new_sqlite_classes: ["VoiceAgent"] }],
  };
  return `${JSON.stringify(wrangler, null, 2)}\n`;
}
