// SPDX-License-Identifier: MIT
//
// Builds .env.example naming exactly the keys the chosen combination needs
// (LDT-21 requirement) — not a union of every provider's keys.

import type { ResolvedOptions } from "../options.js";
import { STT_STAGE_PROVIDERS } from "../providers/stt.js";
import { TTS_STAGE_PROVIDERS } from "../providers/tts.js";
import { REASONER_PROVIDERS } from "../providers/reasoner.js";
import { REALTIME_PROVIDERS } from "../providers/realtime.js";
import { VAD_SIDECAR_PROVIDERS, ENDPOINTING_SIDECAR_PROVIDERS } from "../providers/vad-endpointing.js";
import type { EnvKeySpec } from "../providers/types.js";

export function collectEnvKeys(opts: ResolvedOptions): readonly EnvKeySpec[] {
  const keys: EnvKeySpec[] = [];
  const seen = new Set<string>();
  const add = (specs: readonly EnvKeySpec[]) => {
    for (const spec of specs) {
      if (seen.has(spec.key)) continue;
      seen.add(spec.key);
      keys.push(spec);
    }
  };

  if (opts.mode === "cascade") {
    const stt = STT_STAGE_PROVIDERS[opts.stt];
    const tts = TTS_STAGE_PROVIDERS[opts.tts];
    const reasoner = REASONER_PROVIDERS[opts.reasoner];
    if (stt) add(stt.envKeys);
    if (tts) add(tts.envKeys);
    if (reasoner) add(reasoner.envKeys);
    const vad = opts.vad !== undefined ? VAD_SIDECAR_PROVIDERS[opts.vad] : undefined;
    if (vad) add(vad.envKeys);
    const eos = opts.endpointing !== undefined ? ENDPOINTING_SIDECAR_PROVIDERS[opts.endpointing] : undefined;
    if (eos) add(eos.envKeys);
  } else {
    const realtime = REALTIME_PROVIDERS[opts.realtime];
    if (realtime) add(realtime.envKeys);
  }

  return keys;
}

export function buildEnvExample(opts: ResolvedOptions): string {
  const keys = collectEnvKeys(opts);
  const lines = [
    "# Generated by create-syrinx-agent — exactly the keys this combination needs.",
    "# Copy to .env and fill in.",
    "",
    ...keys.map((k) => `${k.key}=`),
    "",
    "# Optional — local dev server bind (defaults: 127.0.0.1:4173)",
    "SYRINX_DEV_PORT=",
    "SYRINX_DEV_HOST=",
    "",
  ];
  return `${lines.join("\n")}\n`;
}
